"""IDE stubs: SeleniumBase UC/CDP Mode (install Scraplex[seleniumbase] in active venv)."""

from collections.abc import Generator
from contextlib import contextmanager
from types import ModuleType
from typing import Any, Literal


class CDPWebElement:
    """CDP WebElement session helpers."""

    def clear_input(self) -> None: ...
    def click(self) -> None: ...
    def click_with_offset(self, x: float, y: float, center: bool = False) -> None: ...
    def flash(self, duration: float = 0.5, color: str = "EE4488") -> None: ...
    def focus(self) -> None: ...
    def gui_click(self, timeframe: float = 0.25) -> None: ...
    def highlight_overlay(self) -> None: ...
    def is_in_viewport(self) -> bool: ...
    def mouse_click(self) -> None: ...
    def mouse_drag(self, destination: Any) -> None: ...
    def mouse_move(self) -> None: ...
    def press_keys(self, text: str) -> None: ...
    def query_selector(self, selector: str) -> CDPWebElement | None: ...
    def querySelector(self, selector: str) -> CDPWebElement | None: ...
    def query_selector_all(self, selector: str) -> list[CDPWebElement]: ...
    def querySelectorAll(self, selector: str) -> list[CDPWebElement]: ...
    def remove_from_dom(self) -> None: ...
    def save_screenshot(self, *args: Any, **kwargs: Any) -> None: ...
    def save_to_dom(self) -> None: ...
    def scroll_into_view(self) -> None: ...
    def select_option(self) -> None: ...
    def send_file(self, *file_paths: str) -> None: ...
    def send_keys(self, text: str) -> None: ...
    def set_text(self, value: str) -> None: ...
    def type(self, text: str) -> None: ...
    def get_position(self) -> dict[str, float]: ...
    def get_html(self) -> str: ...
    def get_js_attributes(self) -> dict[str, Any]: ...
    def get_attribute(self, attribute: str) -> str | None: ...
    def get_parent(self) -> CDPWebElement | None: ...


class CDPSession:
    """CDP API on ``sb.cdp`` after ``activate_cdp_mode()`` — stealth, no WebDriver."""

    def get(self, url: str, **kwargs: Any) -> None: ...
    def open(self, url: str, **kwargs: Any) -> None: ...
    def reload(
        self, ignore_cache: bool = True, script_to_evaluate_on_load: str | None = None
    ) -> None: ...
    def refresh(self, *args: Any, **kwargs: Any) -> None: ...
    def get_event_loop(self) -> Any: ...
    def get_rd_host(self) -> str: ...
    def get_rd_port(self) -> int: ...
    def get_rd_url(self) -> str: ...
    def get_endpoint_url(self) -> str: ...
    def get_port(self) -> int: ...
    def get_websocket_url(self) -> str: ...
    def add_handler(self, event: Any, handler: Any) -> None: ...
    def find_element(
        self, selector: str, best_match: bool = False, timeout: float | None = None
    ) -> CDPWebElement: ...
    def find(
        self, selector: str, best_match: bool = False, timeout: float | None = None
    ) -> CDPWebElement: ...
    def locator(
        self, selector: str, best_match: bool = False, timeout: float | None = None
    ) -> CDPWebElement: ...
    def find_element_by_text(
        self, text: str, tag_name: str | None = None, timeout: float | None = None
    ) -> CDPWebElement: ...
    def find_all(self, selector: str, timeout: float | None = None) -> list[CDPWebElement]: ...
    def find_elements_by_text(self, text: str, tag_name: str | None = None) -> list[CDPWebElement]: ...
    def select(self, selector: str, timeout: float | None = None) -> CDPWebElement: ...
    def select_all(self, selector: str, timeout: float | None = None) -> list[CDPWebElement]: ...
    def find_elements(self, selector: str, timeout: float | None = None) -> list[CDPWebElement]: ...
    def find_visible_elements(
        self, selector: str, timeout: float | None = None
    ) -> list[CDPWebElement]: ...
    def click(self, selector: str, timeout: float | None = None, scroll: bool = True) -> None: ...
    def click_if_visible(
        self, selector: str, timeout: float = 0, scroll: bool = True
    ) -> None: ...
    def click_visible_elements(self, selector: str, limit: int = 0, scroll: bool = True) -> None: ...
    def click_nth_element(self, selector: str, number: int, scroll: bool = True) -> None: ...
    def click_nth_visible_element(self, selector: str, number: int, scroll: bool = True) -> None: ...
    def click_with_offset(
        self, selector: str, x: float, y: float, center: bool = False, scroll: bool = True
    ) -> None: ...
    def click_link(self, link_text: str) -> None: ...
    def go_back(self) -> None: ...
    def go_forward(self) -> None: ...
    def get_navigation_history(self) -> list[Any]: ...
    def tile_windows(self, windows: list[Any] | None = None, max_columns: int = 0) -> None: ...
    def grant_permissions(self, permissions: list[str], origin: str | None = None) -> None: ...
    def grant_all_permissions(self) -> None: ...
    def reset_permissions(self) -> None: ...
    def get_all_cookies(self, *args: Any, **kwargs: Any) -> list[dict[str, Any]]: ...
    def set_all_cookies(self, *args: Any, **kwargs: Any) -> None: ...
    def save_cookies(self, *args: Any, **kwargs: Any) -> None: ...
    def load_cookies(self, *args: Any, **kwargs: Any) -> None: ...
    def clear_cookies(self) -> None: ...
    def sleep(self, seconds: float) -> None: ...
    def bring_active_window_to_front(self) -> None: ...
    def bring_to_front(self) -> None: ...
    def get_active_element(self) -> CDPWebElement | None: ...
    def get_active_element_css(self) -> str: ...
    def click_active_element(self) -> None: ...
    def mouse_click(
        self, selector: str, timeout: float | None = None, scroll: bool = True
    ) -> None: ...
    def nested_click(self, parent_selector: str, selector: str) -> None: ...
    def get_nested_element(self, parent_selector: str, selector: str) -> CDPWebElement: ...
    def select_option_by_text(self, dropdown_selector: str, option: str) -> None: ...
    def select_option_by_index(self, dropdown_selector: str, option: int) -> None: ...
    def select_option_by_value(self, dropdown_selector: str, option: str) -> None: ...
    def flash(
        self, selector: str, duration: float = 1, color: str = "44CC88", pause: float = 0
    ) -> None: ...
    def highlight(self, selector: str) -> None: ...
    def focus(self, selector: str) -> None: ...
    def highlight_overlay(self, selector: str) -> None: ...
    def get_parent(self, element: Any) -> CDPWebElement | None: ...
    def remove_element(self, selector: str) -> None: ...
    def remove_from_dom(self, selector: str) -> None: ...
    def remove_elements(self, selector: str) -> None: ...
    def send_keys(self, selector: str, text: str, timeout: float | None = None) -> None: ...
    def press_keys(self, selector: str, text: str, timeout: float | None = None) -> None: ...
    def type(self, selector: str, text: str, timeout: float | None = None) -> None: ...
    def set_value(self, selector: str, text: str, timeout: float | None = None) -> None: ...
    def clear_input(self, selector: str, timeout: float | None = None) -> None: ...
    def clear(self, selector: str, timeout: float | None = None) -> None: ...
    def submit(self, selector: str) -> None: ...
    def evaluate(self, expression: str) -> Any: ...
    def execute_script(self, expression: str) -> Any: ...
    def js_dumps(self, obj_name: str) -> Any: ...
    def maximize(self) -> None: ...
    def minimize(self) -> None: ...
    def medimize(self) -> None: ...
    def set_window_rect(self, x: int, y: int, width: int, height: int) -> None: ...
    def reset_window_size(self) -> None: ...
    def open_new_window(self, url: str | None = None, switch_to: bool = True) -> Any: ...
    def switch_to_window(self, window: Any) -> None: ...
    def switch_to_newest_window(self) -> None: ...
    def open_new_tab(self, url: str | None = None, switch_to: bool = True) -> Any: ...
    def switch_to_tab(self, tab: Any) -> None: ...
    def switch_to_newest_tab(self) -> None: ...
    def close_active_tab(self) -> None: ...
    def get_active_tab(self) -> Any: ...
    def get_tabs(self) -> list[Any]: ...
    def get_window(self) -> Any: ...
    def get_text(self, selector: str = "body") -> str: ...
    def get_title(self) -> str: ...
    def get_current_url(self) -> str: ...
    def get_origin(self) -> str: ...
    def get_html(self, include_shadow_dom: bool = True) -> str: ...
    def get_page_source(self, include_shadow_dom: bool = True) -> str: ...
    def get_beautiful_soup(self, source: str | None = None) -> Any: ...
    def get_user_agent(self) -> str: ...
    def get_cookie_string(self) -> str: ...
    def get_locale_code(self) -> str: ...
    def get_local_storage_item(self, key: str) -> str | None: ...
    def get_session_storage_item(self, key: str) -> str | None: ...
    def get_screen_rect(self) -> dict[str, int]: ...
    def get_window_rect(self) -> dict[str, int]: ...
    def get_window_size(self) -> dict[str, int]: ...
    def get_window_position(self) -> dict[str, int]: ...
    def get_element_rect(self, selector: str, timeout: float | None = None) -> dict[str, float]: ...
    def get_element_size(self, selector: str, timeout: float | None = None) -> dict[str, float]: ...
    def get_element_position(
        self, selector: str, timeout: float | None = None
    ) -> dict[str, float]: ...
    def get_gui_element_rect(
        self, selector: str, timeout: float | None = None
    ) -> dict[str, float]: ...
    def get_gui_element_center(
        self, selector: str, timeout: float | None = None
    ) -> dict[str, float]: ...
    def get_document(self) -> Any: ...
    def get_flattened_document(self) -> Any: ...
    def get_element_attributes(self, selector: str) -> dict[str, str]: ...
    def get_element_attribute(self, selector: str, attribute: str) -> str | None: ...
    def get_attribute(self, selector: str, attribute: str) -> str | None: ...
    def get_element_html(self, selector: str) -> str: ...
    def get_mfa_code(self, totp_key: str | None = None) -> str: ...
    def enter_mfa_code(
        self, selector: str, totp_key: str | None = None, timeout: float | None = None
    ) -> None: ...
    def activate_messenger(self) -> None: ...
    def set_messenger_theme(self, theme: str = "default", location: str = "default") -> None: ...
    def post_message(
        self, message: str, duration: float | None = None, pause: bool = True, style: str = "info"
    ) -> None: ...
    def set_locale(self, locale: str) -> None: ...
    def set_local_storage_item(self, key: str, value: str) -> None: ...
    def set_session_storage_item(self, key: str, value: str) -> None: ...
    def set_attributes(self, selector: str, attribute: str, value: str) -> None: ...
    def is_attribute_present(
        self, selector: str, attribute: str, value: str | None = None
    ) -> bool: ...
    def is_online(self) -> bool: ...
    def solve_captcha(self) -> None: ...
    def click_captcha(self) -> None: ...
    def gui_press_key(self, key: str) -> None: ...
    def gui_press_keys(self, keys: str) -> None: ...
    def gui_write(self, text: str) -> None: ...
    def gui_click_x_y(self, x: float, y: float, timeframe: float = 0.25) -> None: ...
    def gui_click_element(self, selector: str, timeframe: float = 0.25) -> None: ...
    def gui_click_with_offset(
        self, selector: str, x: float, y: float, timeframe: float = 0.25, center: bool = False
    ) -> None: ...
    def gui_click_captcha(self) -> None: ...
    def gui_drag_drop_points(
        self, x1: float, y1: float, x2: float, y2: float, timeframe: float = 0.35
    ) -> None: ...
    def gui_drag_and_drop(
        self, drag_selector: str, drop_selector: str, timeframe: float = 0.35
    ) -> None: ...
    def gui_click_and_hold(self, selector: str, timeframe: float = 0.35) -> None: ...
    def gui_hover_x_y(self, x: float, y: float) -> None: ...
    def gui_hover_element(self, selector: str) -> None: ...
    def gui_hover_and_click(self, hover_selector: str, click_selector: str) -> None: ...
    def hover_element(self, selector: str) -> None: ...
    def hover_and_click(self, hover_selector: str, click_selector: str) -> None: ...
    def internalize_links(self) -> None: ...
    def is_checked(self, selector: str) -> bool: ...
    def is_selected(self, selector: str) -> bool: ...
    def check_if_unchecked(self, selector: str) -> None: ...
    def select_if_unselected(self, selector: str) -> None: ...
    def uncheck_if_checked(self, selector: str) -> None: ...
    def unselect_if_selected(self, selector: str) -> None: ...
    def is_element_present(self, selector: str) -> bool: ...
    def is_element_visible(self, selector: str) -> bool: ...
    def is_text_visible(self, text: str, selector: str = "body") -> bool: ...
    def is_exact_text_visible(self, text: str, selector: str = "body") -> bool: ...
    def wait_for_text(self, text: str, selector: str = "body", timeout: float | None = None) -> None: ...
    def wait_for_text_not_visible(
        self, text: str, selector: str = "body", timeout: float | None = None
    ) -> None: ...
    def wait_for_element_visible(self, selector: str, timeout: float | None = None) -> None: ...
    def wait_for_element(self, selector: str, timeout: float | None = None) -> None: ...
    def wait_for_element_not_visible(self, selector: str, timeout: float | None = None) -> None: ...
    def wait_for_element_absent(self, selector: str, timeout: float | None = None) -> None: ...
    def wait_for_any_of_elements_visible(self, *args: Any, **kwargs: Any) -> None: ...
    def wait_for_any_of_elements_present(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_of_elements_visible(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_any_of_elements_present(self, *args: Any, **kwargs: Any) -> None: ...
    def assert_element(self, selector: str, timeout: float | None = None) -> None: ...
    def assert_element_visible(self, selector: str, timeout: float | None = None) -> None: ...
    def assert_element_present(self, selector: str, timeout: float | None = None) -> None: ...
    def assert_element_absent(self, selector: str, timeout: float | None = None) -> None: ...
    def assert_element_not_visible(self, selector: str, timeout: float | None = None) -> None: ...
    def assert_element_attribute(
        self, selector: str, attribute: str, value: str | None = None
    ) -> None: ...
    def assert_title(self, title: str) -> None: ...
    def assert_title_contains(self, substring: str) -> None: ...
    def assert_url(self, url: str) -> None: ...
    def assert_url_contains(self, substring: str) -> None: ...
    def assert_text(self, text: str, selector: str = "html", timeout: float | None = None) -> None: ...
    def assert_exact_text(
        self, text: str, selector: str = "html", timeout: float | None = None
    ) -> None: ...
    def assert_text_not_visible(
        self, text: str, selector: str = "body", timeout: float | None = None
    ) -> None: ...
    def assert_true(self, expr: Any, msg: str | None = None) -> None: ...
    def assert_false(self, expr: Any, msg: str | None = None) -> None: ...
    def assert_equal(self, first: Any, second: Any) -> None: ...
    def assert_not_equal(self, first: Any, second: Any) -> None: ...
    def assert_in(self, first: Any, second: Any) -> None: ...
    def assert_not_in(self, first: Any, second: Any) -> None: ...
    def js_scroll_into_view(self, selector: str) -> None: ...
    def scroll_into_view(self, selector: str) -> None: ...
    def scroll_to_y(self, y: float) -> None: ...
    def scroll_to_top(self) -> None: ...
    def scroll_to_bottom(self) -> None: ...
    def scroll_up(self, amount: float = 25) -> None: ...
    def scroll_down(self, amount: float = 25) -> None: ...
    def save_page_source(self, name: str, folder: str | None = None) -> None: ...
    def save_as_html(self, name: str, folder: str | None = None) -> None: ...
    def save_screenshot(
        self, name: str, folder: str | None = None, selector: str | None = None
    ) -> None: ...
    def print_to_pdf(self, name: str, folder: str | None = None) -> None: ...
    def save_as_pdf(self, name: str, folder: str | None = None) -> None: ...


class BaseCase:
    """UC Mode session from ``SB(uc=True)`` — use ``activate_cdp_mode`` for stealth."""

    driver: Any
    cdp: CDPSession

    def activate_cdp_mode(self, url: str | None = None, **kwargs: Any) -> None:
        """Disconnect WebDriver; enable ``sb.cdp`` stealth methods (recommended entry)."""
        ...

    def solve_captcha(self) -> None:
        """Solve CAPTCHA (uses CDP when in CDP Mode)."""
        ...

    def reconnect(self) -> None:
        """Reconnect WebDriver (may trigger bot detection)."""
        ...

    def disconnect(self) -> None:
        """Disconnect WebDriver; use CDP methods."""
        ...

    def connect(self) -> None:
        """Alias for reconnect()."""
        ...

    def is_connected(self) -> bool:
        """True when WebDriver is connected to the browser."""
        ...

    def open(self, url: str, **kwargs: Any) -> None:
        """Open URL (UC Mode; also activates CDP Mode in recent SeleniumBase)."""
        ...

    def get_page_source(self, *args: Any, **kwargs: Any) -> str:
        """Page HTML (routes to CDP when disconnected)."""
        ...

    def get_page_title(self) -> str:
        """Document title."""
        ...

    def get_current_url(self) -> str:
        """Current URL."""
        ...

    def click(self, selector: str, **kwargs: Any) -> None:
        """Click (redirects to CDP when disconnected)."""
        ...

    def click_if_visible(self, selector: str, **kwargs: Any) -> None:
        """Click if visible."""
        ...

    def type(self, selector: str, text: str, **kwargs: Any) -> None:
        """Type text."""
        ...

    def press_keys(self, selector: str, text: str, **kwargs: Any) -> None:
        """Human-speed key entry."""
        ...

    def sleep(self, seconds: float) -> None:
        """Pause execution."""
        ...

    def select_all(self, selector: str, **kwargs: Any) -> list[Any]:
        """All matching elements."""
        ...

    def is_element_visible(self, selector: str) -> bool:
        """Whether selector is visible."""
        ...

    def wait_for_element_visible(self, selector: str, timeout: float | None = None) -> None:
        """Wait until selector is visible."""
        ...

    def scroll_into_view(self, selector: str) -> None:
        """Scroll element into view."""
        ...

    def quit(self) -> None:
        """Close browser session."""
        ...


class _SbCdpChrome(CDPSession):
    """Pure CDP browser from ``sb_cdp.Chrome(url)`` — no WebDriver."""

    driver: Any


class _SbCdpModule(ModuleType):
    """Pure CDP Mode — ``fetch.sb_cdp.Chrome(url)``."""

    def Chrome(self, url: str | None = None, **kwargs: Any) -> _SbCdpChrome:
        """Launch browser via CDP only (no WebDriver)."""
        ...


class _AsyncTab:
    """Async CDP page / tab object."""

    async def get(self, url: str = "about:blank", **kwargs: Any) -> None: ...
    async def open(self, url: str = "about:blank", **kwargs: Any) -> None: ...
    async def find(self, text: str, best_match: bool = False, timeout: float = 10) -> Any: ...
    async def find_all(self, text: str, timeout: float = 10) -> list[Any]: ...
    async def select(self, selector: str, timeout: float = 10) -> Any: ...
    async def select_all(
        self, selector: str, timeout: float = 10, include_frames: bool = False
    ) -> list[Any]: ...
    async def query_selector(self, selector: str) -> Any: ...
    async def query_selector_all(self, selector: str) -> list[Any]: ...
    async def find_element_by_text(self, text: str, best_match: bool = False) -> Any: ...
    async def find_elements_by_text(self, text: str) -> list[Any]: ...
    async def reload(
        self, ignore_cache: bool = True, script_to_evaluate_on_load: str | None = None
    ) -> None: ...
    async def evaluate(self, expression: str) -> Any: ...
    async def js_dumps(self, obj_name: str) -> Any: ...
    async def back(self) -> None: ...
    async def forward(self) -> None: ...
    async def get_window(self) -> Any: ...
    async def get_content(self) -> str: ...
    async def maximize(self) -> None: ...
    async def minimize(self) -> None: ...
    async def fullscreen(self) -> None: ...
    async def medimize(self) -> None: ...
    async def set_window_size(
        self, left: int = 0, top: int = 0, width: int = 1280, height: int = 1024
    ) -> None: ...
    async def set_window_rect(
        self, left: int = 0, top: int = 0, width: int = 1280, height: int = 1024
    ) -> None: ...
    async def activate(self) -> None: ...
    async def bring_to_front(self) -> None: ...
    async def set_window_state(
        self, left: int = 0, top: int = 0, width: int = 1280, height: int = 720, state: str = "normal"
    ) -> None: ...
    async def get_navigation_history(self) -> list[Any]: ...
    async def get_user_agent(self) -> str: ...
    async def get_cookie_string(self) -> str: ...
    async def get_locale_code(self) -> str: ...
    async def is_online(self) -> bool: ...
    async def open_external_inspector(self) -> None: ...
    async def close(self) -> None: ...
    async def scroll_down(self, amount: float = 25) -> None: ...
    async def scroll_up(self, amount: float = 25) -> None: ...
    async def wait_for(self, selector: str = "", text: str = "", timeout: float = 10) -> None: ...
    async def set_attributes(self, selector: str, attribute: str, value: str) -> None: ...
    async def internalize_links(self) -> None: ...
    async def download_file(self, url: str, filename: str | None = None) -> None: ...
    async def save_screenshot(
        self, filename: str = "auto", format: str = "png", full_page: bool = False
    ) -> None: ...
    async def print_to_pdf(self, filename: str = "auto") -> None: ...
    async def set_download_path(self, path: str) -> None: ...
    async def get_all_linked_sources(self) -> list[str]: ...
    async def get_all_urls(self, absolute: bool = True) -> list[str]: ...
    async def get_html(self) -> str: ...
    async def get_page_source(self) -> str: ...
    async def is_element_present(self, selector: str) -> bool: ...
    async def is_element_visible(self, selector: str) -> bool: ...
    async def get_element_rect(self, selector: str, timeout: float = 5) -> dict[str, float]: ...
    async def get_window_rect(self) -> dict[str, int]: ...
    async def get_gui_element_rect(self, selector: str, timeout: float = 5) -> dict[str, float]: ...
    async def get_title(self) -> str: ...
    async def get_current_url(self) -> str: ...
    async def get_origin(self) -> str: ...
    async def send_keys(self, selector: str, text: str, timeout: float = 5) -> None: ...
    async def type(self, selector: str, text: str, timeout: float = 5) -> None: ...
    async def click(self, selector: str, timeout: float = 5) -> None: ...
    async def click_if_visible(self, selector: str, timeout: float = 0) -> None: ...
    async def click_with_offset(
        self, selector: str, x: float, y: float, center: bool = False, timeout: float = 5
    ) -> None: ...
    async def solve_captcha(self) -> None: ...
    async def click_captcha(self) -> None: ...
    async def get_document(self) -> Any: ...
    async def get_flattened_document(self) -> Any: ...
    async def get_local_storage(self) -> Any: ...
    async def set_local_storage(self, items: Any) -> None: ...


class _CdpDriverModule(ModuleType):
    """Async CDP driver — ``await cdp_driver.start_async()``."""

    async def start_async(self, **kwargs: Any) -> _AsyncTab:
        """Start async CDP driver."""
        ...


class SeleniumBaseProxy:
    """seleniumbase — UC Mode + CDP Mode (same as ``import seleniumbase``).

    **Not** plain ``Driver()`` for anti-bot work. Use UC+CDP:

        fetch = Fetch(engine="seleniumbase")
        with fetch.SB(uc=True, test=True) as sb:
            sb.activate_cdp_mode("https://example.com")
            sb.solve_captcha()
            html = sb.get_page_source()
            sb.cdp.click("button.submit")

    Pure CDP: ``sb = fetch.sb_cdp.Chrome(url)`` · Async: ``fetch.cdp_driver``

    Docs: https://github.com/seleniumbase/SeleniumBase/blob/master/examples/cdp_mode/ReadMe.md
    """

    __version__: str
    BaseCase: type[BaseCase]
    sb_cdp: _SbCdpModule
    cdp_driver: _CdpDriverModule
    decorators: ModuleType
    common: ModuleType
    config: ModuleType
    core: ModuleType
    fixtures: ModuleType
    page_actions: ModuleType
    version_info: tuple[int, ...]

    @contextmanager
    def SB(
        self,
        *,
        uc: bool | None = True,
        test: bool | None = None,
        headless: bool | None = None,
        browser: Literal["chrome", "edge", "firefox", "safari"] | None = None,
        locale_code: str | None = None,
        guest_mode: bool | None = None,
        ad_block_on: bool | None = None,
        proxy: str | None = None,
        **kwargs: Any,
    ) -> Generator[BaseCase, None, None]:
        """UC Mode context manager — pair with ``activate_cdp_mode(url)``."""
        ...

    def Driver(self, **kwargs: Any) -> Any:
        """Legacy WebDriver factory — prefer ``SB(uc=True)`` + CDP Mode."""
        ...

    def get_driver(self, **kwargs: Any) -> Any:
        """Low-level WebDriver — prefer ``SB(uc=True)`` + CDP Mode."""
        ...

    def __init__(self) -> None:
        """Create proxy; requires ``uv sync --extra seleniumbase``."""
        ...

    def __getattr__(self, name: str) -> Any: ...

    @property
    def id(self) -> str: ...

    def installed(self) -> bool: ...
