name: Upload Python Package

on:
  push:
    tags:
      - "*.*.*"
      - "!*.*.*a*"
      - "!*.*.*b*"
      - "!*.*.*rc*"


permissions:
  contents: read # Required to read repository contents
  id-token: write # Required for trusted publishing with OIDC

jobs:
  deploy:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Build package
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0
        with:
          packages-dir: dist/
